platform :ios, '13.0'
use_frameworks!
inhibit_all_warnings!

    # Pods for StepsTest
def common_pods
    
    # Networking
    pod 'Alamofire'
    pod 'Moya'
    pod 'SwiftyJSON', '~> 4.0'
    
    # UI
    pod 'SVProgressHUD'
    pod 'Kingfisher'
    pod 'SnapKit', '~> 5.0.0'
    pod 'SkyFloatingLabelTextField'
    pod 'IQKeyboardManagerSwift'

    # Reactive
    pod 'RxSwift', '~> 5.1.0'
    pod 'RxCocoa', '~> 5.1.0'
    pod 'RxDataSources', '~> 4.0'
    
end

target 'StepsTest' do
    common_pods
end

target 'StepsTestTests' do
    common_pods
end

